src/tweets/urls.py

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from .views import (TweetListView,
                    TweetDetailView,
                    TweetCreateView, 
                    TweetUpdateView, 
                    TweetDeleteView,
                    RetweetView)

app_name = "tweets"

urlpatterns = [
    url(r'^search/$', TweetListView.as_view(), name="list"),
    url(r'^$', RedirectView.as_view(url="/tweet/list/")),
    url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name="detail"),
    url(r'^create/$', TweetCreateView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name="delete"),
    url(r'^(?P<pk>\d+)/retweet/$', RetweetView.as_view(), name='retweet'),
    
]



src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} My Blog {% endblock title %}</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .green-class {
        color: green;
      }
      .red-class {
        color: red;
      }
      .grey-class {
        color: grey;
      }

      .grey-class a {
        color: grey;
      }


    </style>

  </head>
  <body>
    

    <div class="container">
        {% include "navbar.html" %}
        {% block body %}
            
        {% endblock body %}
    </div>

    {% include "reply-modal.html" %}
    


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% block script %} {% endblock script %}
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'tweets/js/tweets_list.js' %}"></script>

    <script>
        
        // Array Remove - By John Resig (MIT Licensed)
        Array.prototype.remove = function(from, to) {
          var rest = this.slice((to || from) + 1 || this.length);
          this.length = from < 0 ? this.length + from : from;
          return this.push.apply(this, rest);
        };

        
        
        function autoTypeSearch () {
            var typingTimer;
            var doneInterval = 800;
            var searchInput = $(".navbar-form input[type=text]");
            var searchQuery;
      
            searchInput.keyup(function (event) {
              searchQuery = $(this).val();
              clearTimeout(typingTimer);
              typingTimer = setTimeout(doneSearchString, doneInterval)
      
            });
      
            searchInput.keydown(function (event) {
              console.log(event.key);
              clearTimeout(typingTimer);
      
            });
      
            


            // change this to fit the user own tweet filter search
            function doneSearchString() {
              if (searchQuery){
                //url = "/tweet/search/?q="+searchQuery;
                let nanikore = document.location.href;
                nanikore = nanikore.split("?")[0];
                nanikore = nanikore.split("/");
                nanikore.remove(0, 2);
                if (nanikore[nanikore.length - 1] === ""){
                  nanikore.remove(-1);
                  
                }

                nanikore = "/" + nanikore.join("/")  + "/";
                nanikore = nanikore + "?q="+searchQuery;
                
                console.log(nanikore);
                document.location.href = nanikore;
              }
            }
        }

        $(document).ready(function(){
          autoTypeSearch();

        });
    

    </script>
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% block body %}
    <h1>Hello world </h1>
{% endblock body %} 

src/templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'tweets:list' %}">Blog</a>
      </div>

      {% include "tweets/search_form.html" %}
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          {% if request.user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{{ request.user.profile.get_absolute_url }}">Profile</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'logout' %}">Logout</a></li>
                </ul>
              </li>
            </ul>
    
          {% else %}
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'login' %}">Login</a></li>
              <li><a href="{% url 'register' %}">Register</a></li>
            </ul>
          {% endif %}


      
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

src/templates/reply-modal.html
<!-- Modal -->
<div class="modal fade" id="replyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
       <form class='form tweet-form'> {% csrf_token %}
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="replyModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
       
          <textarea id='tweetReplyArea' class='form-control' name='content'></textarea>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary" value='Reply'>
      </div>
      </form>
    </div>
  </div>
</div>